#name: Run Tests
#
#on:
#  push:
#    branches: [ main, master, develop ]
#  pull_request:
#    branches: [ main, master, develop ]
#  workflow_dispatch:
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#      - run: chmod +x gradlew
#      - uses: gradle/actions/setup-gradle@v3
#      - run: ./gradlew test
#      - uses: actions/upload-artifact@v4
#        with:
#          name: test-results
#          path: app/build/reports/tests/test/
